info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /user/createUser:
    post:
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      - description: 确认密码
        in: query
        name: repassWord
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 新增用户
      tags:
      - 用户模块
  /user/getUserList:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 所有用户
      tags:
      - 获取用户列表
swagger: "2.0"
